name: Generate Snake (simple)

on:
  schedule:
    - cron: "0 0 * * *"   # jalan tiap hari
  workflow_dispatch:       # bisa run manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sudipa12343
          outputs: dist/snake.svg

      - name: Commit and Push snake.svg
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update snake animation"
          add: "dist/snake.svg"
          push: true
