name: Generate Snake (simple)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sudipa12343
          outputs: dist/snake.svg

      - name: Commit and Push snake.svg
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update snake animation"
          add: "dist/snake.svg"
          push: true
